In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

### Summarizing and Computing Descriptive Statistics

Pandas objects are equipped with a set of common mathematical and statistical meth‐
ods. Most of these fall into the category of reductions or summary statistics, methods
that extract a single value (like the sum or mean) from a Series, or a Series of values
from the rows or columns of a DataFrame.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], 
                   [np.nan, np.nan], [0.75, -1.3]], 
                  index=["a", "b", "c", "d"], 
                  columns=["one", "two"])

print(df)

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [8]:
# sum method returns a Series containing column sums

print(df.sum())

print(df.sum(axis="columns"))

# When an entire row or column contains all NA values, the sum is 0, whereas if any
# value is not NA, then the result is NA. This can be disabled with the skipna option, in
# which case any NA value in a row or column names the corresponding result NA

print(df.sum(axis="index", skipna=False))

print(df.sum(axis="columns", skipna=False))

one    9.25
two   -5.80
dtype: float64
a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64
one   NaN
two   NaN
dtype: float64
a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [10]:
# Some aggregations, like mean, require at least one non-NA value to yield a value
# result

print(df.mean())

print(df.mean(axis="columns"))

one    3.083333
two   -2.900000
dtype: float64
a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

**Options for reduction methods**

* **axis** Axis to reduce over; “index” for DataFrame’s rows and “columns” for columns
* **skipna** Exclude missing values; True by default
* **level** Reduce grouped by level if the axis is hierarchically indexed (MultiIndex)

In [16]:
# idxmin and idxmax, return indirect statistics, like the index value
# where the minimum or maximum values are attained
print(df)
print(df.idxmin())
print(df.idxmax())

print('accumulations: cummulative sums')

print(df.cumsum())

# describe produces multiple summary statistics

print(df.describe())

# On nonnumeric data, describe produces alternative summary statistics

obj = pd.Series(["a", "a", "b", "c"] * 4)

print(obj)

print(obj.describe())

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3
one    d
two    b
dtype: object
one    b
two    d
dtype: object
accumulations: cummulative sums
    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8
            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000
0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object
count     16
unique     3
top        a
freq       8
dtype: object

#### Descriptive and summary statistics

* **count** Number of non-NA values
* **describe** Compute set of summary statistics
* **min, max** Compute minimum and maximum values
* **argmin, argmax** Compute index locations (integers) at which minimum or maximum value is obtained, respectively; not available on DataFrame objects
* **idxmin, idxmax** Compute index labels at which minimum or maximum value is obtained, respectively
* **quantile** Compute sample quantile ranging from 0 to 1 (default: 0.5)
* **sum** Sum of values
* **mean** Mean of values
* **median** Arithmetic median (50% quantile) of values
* **mad** Mean absolute deviation from mean value
* **prod** Product of all values
* **var** Sample variance of values
* **std** Sample standard deviation of values
* **skew** Sample skewness (third moment) of values
* **kurt** Sample kurtosis (fourth moment) of values
* **cumsum** Cumulative sum of values
* **cummin**, cummax Cumulative minimum or maximum of values, respectively
* **cumprod** Cumulative product of values
* **diff** Compute first arithmetic difference (useful for time series)
* **pct_change** Compute percent changes