In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

### Summarizing and Computing Descriptive Statistics

Pandas objects are equipped with a set of common mathematical and statistical meth‐
ods. Most of these fall into the category of reductions or summary statistics, methods
that extract a single value (like the sum or mean) from a Series, or a Series of values
from the rows or columns of a DataFrame.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], 
                   [np.nan, np.nan], [0.75, -1.3]], 
                  index=["a", "b", "c", "d"], 
                  columns=["one", "two"])

print(df)

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [8]:
# sum method returns a Series containing column sums

print(df.sum())

print(df.sum(axis="columns"))

# When an entire row or column contains all NA values, the sum is 0, whereas if any
# value is not NA, then the result is NA. This can be disabled with the skipna option, in
# which case any NA value in a row or column names the corresponding result NA

print(df.sum(axis="index", skipna=False))

print(df.sum(axis="columns", skipna=False))

one    9.25
two   -5.80
dtype: float64
a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64
one   NaN
two   NaN
dtype: float64
a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [10]:
# Some aggregations, like mean, require at least one non-NA value to yield a value
# result

print(df.mean())

print(df.mean(axis="columns"))

one    3.083333
two   -2.900000
dtype: float64
a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

**Options for reduction methods**

* **axis** Axis to reduce over; “index” for DataFrame’s rows and “columns” for columns
* **skipna** Exclude missing values; True by default
* **level** Reduce grouped by level if the axis is hierarchically indexed (MultiIndex)

In [16]:
# idxmin and idxmax, return indirect statistics, like the index value
# where the minimum or maximum values are attained
print(df)
print(df.idxmin())
print(df.idxmax())

print('accumulations: cummulative sums')

print(df.cumsum())

# describe produces multiple summary statistics

print(df.describe())

# On nonnumeric data, describe produces alternative summary statistics

obj = pd.Series(["a", "a", "b", "c"] * 4)

print(obj)

print(obj.describe())

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3
one    d
two    b
dtype: object
one    b
two    d
dtype: object
accumulations: cummulative sums
    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8
            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000
0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object
count     16
unique     3
top        a
freq       8
dtype: object

#### Descriptive and summary statistics

* **count** Number of non-NA values
* **describe** Compute set of summary statistics
* **min, max** Compute minimum and maximum values
* **argmin, argmax** Compute index locations (integers) at which minimum or maximum value is obtained, respectively; not available on DataFrame objects
* **idxmin, idxmax** Compute index labels at which minimum or maximum value is obtained, respectively
* **quantile** Compute sample quantile ranging from 0 to 1 (default: 0.5)
* **sum** Sum of values
* **mean** Mean of values
* **median** Arithmetic median (50% quantile) of values
* **mad** Mean absolute deviation from mean value
* **prod** Product of all values
* **var** Sample variance of values
* **std** Sample standard deviation of values
* **skew** Sample skewness (third moment) of values
* **kurt** Sample kurtosis (fourth moment) of values
* **cumsum** Cumulative sum of values
* **cummin**, cummax Cumulative minimum or maximum of values, respectively
* **cumprod** Cumulative product of values
* **diff** Compute first arithmetic difference (useful for time series)
* **pct_change** Compute percent changes

### Correlation and Covariance

Some summary statistics, like correlation and covariance, are computed from pairs
of arguments.

In [20]:
price = pd.read_pickle("/kaggle/input/yahoo-finance/yahoo_price.pkl")
volume = pd.read_pickle("/kaggle/input/yahoo-finance/yahoo_volume.pkl")

In [25]:
returns = price.pct_change()
print(price)
print(returns)

                  AAPL        GOOG         IBM       MSFT
Date
2010-01-04   27.990226  313.062468  113.304536  25.884104
2010-01-05   28.038618  311.683844  111.935822  25.892466
2010-01-06   27.592626  303.826685  111.208683  25.733566
2010-01-07   27.541619  296.753749  110.823732  25.465944
2010-01-08   27.724725  300.709808  111.935822  25.641571
...                ...         ...         ...        ...
2016-10-17  117.550003  779.960022  154.770004  57.220001
2016-10-18  117.470001  795.260010  150.720001  57.660000
2016-10-19  117.120003  801.500000  151.259995  57.529999
2016-10-20  117.059998  796.969971  151.520004  57.250000
2016-10-21  116.599998  799.369995  149.630005  59.660000

[1714 rows x 4 columns]
                AAPL      GOOG       IBM      MSFT
Date
2010-01-04       NaN       NaN       NaN       NaN
2010-01-05  0.001729 -0.004404 -0.012080  0.000323
2010-01-06 -0.015906 -0.025209 -0.006496 -0.006137
2010-01-07 -0.001849 -0.023280 -0.003462 -0.010400
2010-01-08  0.006648  0.013331  0.010035  0.006897
...              ...       ...       ...       ...
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

[1714 rows x 4 columns]

In [26]:
print("correlation between MSFT and IBM")
print(returns["MSFT"].corr(returns["IBM"]))

correlation between MSFT and IBM
0.49976361144151144